### PR TITLE
Write detailed error to the output and also generate a JSON dump file.

### PR DESCRIPTION
**Pull request by ShogunPanda**
Hi!
I extended this utility to show a detailed output in case of errors.

Additionally, it also dumps the error in a JSON file on the current directory (that is removed on process exit or after a successful build). The usage of this is to make other server processes (in my case is Rails) to be aware that the process failed and therefore behave like the assets pipeline and raise a error on the browser.

Hope you're gonna like it.
See ya!
Paolo

### CODE REVIEW

**Comment by ShogunPanda** [comment]
Any update on this?

**Comment by ShogunPanda** [comment]
I second this: any update on this? :)

**Comment by rwjblue** [comment]
Thanks!

**Comment by ShogunPanda** [comment]
Wow! Really fast response! ^^
Honored to had this accepted.

Any plan on when are you gonna release the new npm package? I'd like to use this at work without having dependency on the git repo.

**Comment by sandstrom** [comment]
@rwjblue Thanks for merging this (and @ShogunPanda for authoring)! 😃  It's very useful!

Will a new release be cut soon? (: Using it on master now and it works, but I didn't see this at first because I got the released version.

**Pull request merged**
